name: Reusable Swivel IAC Workflow

on:
  workflow_call:
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Terrafrom plan
        working-directory: ${{ inputs.environment }}
        run: |
          terraform init
          terraform plan -out=tfplan
      
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          timeout-minutes: 60
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: "devops-scaleops"
          minimum-approvals: 1

      - name: Terraform Apply (Manual Approval Required)
        working-directory: ${{ inputs.environment }}
        run:  |
          terraform apply tfplan
